### ISSUE TITLE
Issue installing android-rename on mac

### ISSUE THREAD

**Issue by haseelrefl** [cnzx219/android-rename-package#1]
I get the following while trying to install : 

ld: library not found for -lgcc_s.10.5

NPM Version : 3.5.3

Full log : 

sudo npm -g install android-rename
Password:
/usr/local/bin/rp -> /usr/local/lib/node_modules/android-rename/bin/rp-cli

> node-expat@2.3.12 install /usr/local/lib/node_modules/android-rename/node_modules/node-expat
> node-gyp rebuild

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/node_expat.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [Release/node_expat.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/android-rename/node_modules/node-expat
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "-g" "install" "android-rename"
npm ERR! node v0.10.33
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.3.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.12 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-expat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mohamedhk/android-rename-package/npm-debug.log

**Comment by haseelrefl** [comment]
This was an issue with my nodejs version. Had no luck with updating the version.

Fixed by uninstalling nodeJS completely and installing the latest version of nodeJS again.

Thank you.
